### ISSUE TITLE
ZSchema should be able to validate DateTime ranges

### ISSUE THREAD

**Issue by dadrian** [zmap/zschema#13]
E.g., when running validate and compiling to big query, no times should be past 9999-12-31. https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql#timestamp_differences

**Comment by zakird** [comment]
good call!

**Comment by zakird** [comment]
we should probably set a reasonable minimum date on fields too

**Comment by dadrian** [comment]
BQ also defines a minimum date, which I think is the same as the Golang one.
