### ISSUE TITLE
validate is not strict enough

### ISSUE THREAD

**Issue by dadrian** [zmap/zschema#3]
I have a file that failed validation when updating to BigQuery because a non-leaf node was set to null, rather than omitted. zschema validate does not currently catch this, and passes the file with no errors.

**Comment by zakird** [comment]
Can you please commit a test for this? (it'll fail on master) I'll commit a fix and then once we're in place we should be good.

**Comment by zakird** [comment]
Actually, can you first check and see if this is currently a problem on master? It looks like this already checked.
